# Generated by Django 4.0.2 on 2022-03-24 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_history_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='CustomerHistory',
        ),
    ]
