# Generated by Django 4.0.2 on 2022-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_history_customerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='history',
        ),
        migrations.AddField(
            model_name='books',
            name='history',
            field=models.ManyToManyField(related_name='books', to='home.CustomerHistory'),
        ),
    ]
