# Generated by Django 4.0.2 on 2022-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_books_history_books_customer_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='profane_words',
        ),
        migrations.AddField(
            model_name='books',
            name='total_words',
            field=models.IntegerField(null=True),
        ),
    ]
