# Generated by Django 4.0.2 on 2022-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_books_profane_words_books_total_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='ASIN',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='customer_history',
            field=models.ManyToManyField(blank=True, related_name='books', to='home.CustomerHistory'),
        ),
        migrations.AddField(
            model_name='book',
            name='profane_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=1243, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='total_words',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
